phphants/phph-site

composer.lock
module/Phph/Site/config/module.config.php
module/Phph/Site/src/Controller/MeetupsController.php
module/Phph/Site/view/phph/index/index.phtml
public/.htaccess

I would have had to either called /subscribe in the view and allow the .htaccess to redirect or duplicate the remote url in the view and the htaccess file. So I pulled out of htaccess and added controller action so we could use a named route in the view and the URL only appears in one place.

Added link to subscribe page

---

.gitignore
module/Phph/Site/view/phph/team/index.phtml
public/css/style.css

Update james bio

---

module/Phph/Site/view/phph/team/index.phtml

I've been back on twitter since last November :)

Richard is back on twitter

---

data/meetups/2015-09-09.php

I think this is the only option that is close to the venue and train station @garoevans @richardjh @asgrim

Update September social venue

---

module/Phph/Site/view/layout/footer.phtml
module/Phph/Site/view/phph/videos/index.phtml
public/css/style.css
public/js/scripts.js

Attempt to solve #84 
Simple lazy load script, only loads the embeds on click.
Currently manually concatting the styles and scripts into files but could introduce a build script to handle this. Thought this would be the simplest.
Thoughts?

Lazy loading youtube videos to reduce jank, #84

---

data/meetups/2016-04-13.php
data/meetups/2016-05-11.php

Added future meetups and all that jazz

---

data/meetups/2016-09-14.php

Updated meetups for Aug-Sep 2016

---

config/autoload/dependencies.global.php
data/migrations/Version20160925140055.php
src/App/Action/VideosAction.php
src/App/Action/VideosActionFactory.php
src/App/Entity/Video.php
src/App/Service/Video/DoctrineGetAllVideos.php
src/App/Service/Video/GetAllVideosFactory.php
src/App/Service/Video/GetAllVideosInterface.php
templates/app/videos.phtml
test/AppTest/Action/VideosActionTest.php
test/AppTest/Entity/VideoTest.php
test/AppTest/Service/Videos/DoctrineGetAllVideosTest.php

Fixes #114 
Videos are now stored in the database. Nothing complex here, no admin interface yet (to be convered in #119)

Store videos in database

---

src/App/Service/Speaker/DoctrineGetAllSpeakers.php
test/AppTest/Service/Speaker/DoctrineGetAllSpeakersTest.php

Order speakers alphabetically

---

templates/layout/footer.phtml

If logged in, go to dashboard. If not, go to login.

Make dashboard link in footer better

---

src/App/Service/Speaker/DoctrineGetAllSpeakers.php
test/AppTest/Service/Speaker/DoctrineGetAllSpeakersTest.php

Use correct field name for sorting

---

public/css/admin.css
src/App/Action/Account/Talk/AddTalkAction.php
src/App/Action/Account/Talk/EditTalkAction.php
src/App/Entity/Talk.php
src/App/Form/Account/TalkForm.php
templates/app/account/meetup/view.phtml
test/AppTest/Action/Account/Talk/AddTalkActionTest.php
test/AppTest/Action/Account/Talk/EditTalkActionTest.php
test/AppTest/Entity/TalkTest.php
test/AppTest/Form/Account/TalkFormTest.php

Allow adding YouTube links to talks in admin UI

---

config/autoload/routes.global.php
src/App/Action/Account/Speaker/AddSpeakerAction.php
src/App/Action/Account/Speaker/AddSpeakerActionFactory.php
src/App/Action/Account/Speaker/EditSpeakerAction.php
src/App/Action/Account/Speaker/EditSpeakerActionFactory.php
src/App/Action/Account/Speaker/ListSpeakersAction.php
src/App/Action/Account/Speaker/ListSpeakersActionFactory.php
src/App/Entity/Speaker.php
src/App/Form/Account/SpeakerForm.php
templates/app/account/dashboard.phtml
templates/app/account/speaker/edit.phtml
templates/app/account/speaker/list.phtml
templates/layout/header.phtml
test/AppTest/Action/Account/Speaker/AddSpeakerActionTest.php
test/AppTest/Action/Account/Speaker/EditSpeakerActionTest.php
test/AppTest/Action/Account/Speaker/ListSpeakersActionTest.php
test/AppTest/Entity/SpeakerTest.php
test/AppTest/Form/Account/SpeakerFormTest.php

Speaker management interface

---

public/css/style.css
templates/layout/footer.phtml

Add links for Slack and invite for php.ug

---

composer.json
composer.lock
config/autoload/dependencies.global.php
config/autoload/global.php
data/migrations/Version20161201165930.php
public/css/admin.css
public/images/speakers/.gitignore
src/App/Action/Account/Speaker/AddSpeakerAction.php
src/App/Action/Account/Speaker/AddSpeakerActionFactory.php
src/App/Action/Account/Speaker/EditSpeakerAction.php
src/App/Action/Account/Speaker/EditSpeakerActionFactory.php
src/App/Entity/Speaker.php
src/App/Form/Account/SpeakerForm.php
src/App/Service/Speaker/MoveSpeakerHeadshot.php
src/App/Service/Speaker/MoveSpeakerHeadshotFactory.php
src/App/Service/Speaker/MoveSpeakerHeadshotInterface.php
templates/app/account/speaker/edit.phtml
templates/app/account/speaker/list.phtml
test/AppTest/Action/Account/Speaker/AddSpeakerActionTest.php
test/AppTest/Action/Account/Speaker/EditSpeakerActionTest.php
test/AppTest/Entity/SpeakerTest.php
test/AppTest/Form/Account/SpeakerFormTest.php
test/AppTest/Service/Speaker/MoveSpeakerHeadshotTest.php

Add ability to store bio and headshots with speaker profiles.

Speaker more data storage

---

config/autoload/dependencies.global.php
config/autoload/routes.global.php
data/migrations/Version20170107221613.php
src/App/Entity/User.php
src/App/Service/Authorization/AuthorizationService.php
src/App/Service/Authorization/AuthorizationServiceInterface.php
src/App/Service/Authorization/Factory.php
src/App/Service/Authorization/Middleware/HasAdministratorRoleMiddleware.php
src/App/Service/Authorization/Middleware/HasAdministratorRoleMiddlewareFactory.php
src/App/Service/Authorization/Middleware/HasAttendeeRoleMiddleware.php
src/App/Service/Authorization/Middleware/HasAttendeeRoleMiddlewareFactory.php
src/App/Service/Authorization/Role/AdministratorRole.php
src/App/Service/Authorization/Role/AttendeeRole.php
src/App/Service/Authorization/Role/Exception/InvalidRoleName.php
src/App/Service/Authorization/Role/RoleFactory.php
src/App/Service/Authorization/Role/RoleInterface.php
src/App/View/Helper/User.php
src/App/View/Helper/UserFactory.php
templates/app/account/dashboard.phtml
templates/layout/header.phtml
test/AppTest/Entity/UserTest.php
test/AppTest/Service/Authorization/AuthorizationServiceTest.php
test/AppTest/Service/Authorization/Middleware/HasAdministratorRoleMiddlewareTest.php
test/AppTest/Service/Authorization/Middleware/HasAttendeeRoleMiddlewareTest.php
test/AppTest/Service/Authorization/Role/AdministratorRoleTest.php
test/AppTest/Service/Authorization/Role/AttendeeRoleTest.php
test/AppTest/Service/Authorization/Role/Exception/InvalidRoleNameTest.php
test/AppTest/Service/Authorization/Role/RoleFactoryTest.php
test/AppTest/View/Helper/UserTest.php

Add basic access control to have varying user access levels (attendee and administrator, currently)
Forms part of #102 but does not complete it yet.

Add access control

---

.travis.yml
composer.json
composer.lock
config/autoload/global.php
config/autoload/local.php.dist
config/autoload/routes.global.php
src/App/Action/Account/RegisterAction.php
src/App/Action/Account/RegisterActionFactory.php
src/App/Entity/User.php
src/App/Form/Account/RegisterForm.php
src/App/Service/Authentication/Factory.php
src/App/Service/Authentication/ZendAuthenticationService.php
src/App/Service/GoogleRecaptcha/VerifyGoogleRecaptcha.php
src/App/Service/GoogleRecaptcha/VerifyGoogleRecaptchaInterface.php
src/App/Service/User/PasswordHashInterface.php
src/App/Service/User/PhpPasswordHash.php
src/App/Validator/GoogleRecaptchaValidator.php
templates/app/account/register.phtml
test/AppTest/Action/Account/RegisterActionTest.php
test/AppTest/Entity/UserTest.php
test/AppTest/Form/Account/RegisterFormTest.php
test/AppTest/Service/Authentication/ZendAuthenticationServiceTest.php
test/AppTest/Service/GoogleRecaptcha/VerifyGoogleRecaptchaTest.php
test/AppTest/Service/User/PhpPasswordHashTest.php
test/AppTest/Validator/GoogleRecaptchaValidatorTest.php

Finishes up ability for attendees to login.
They can't actually do anything useful yet, but this forms the basis for logging in and marking self attending (#102)

Registration form

---

src/App/Action/Account/RegisterActionFactory.php
src/App/Form/Account/RegisterForm.php
src/App/Validator/UserDoesNotExistValidator.php
test/AppTest/Form/Account/RegisterFormTest.php
test/AppTest/Validator/UserDoesNotExistValidatorTest.php

Added validator to ensure a user does not already exist

---

composer.json
composer.lock

Fix videos page - doctrine/common was incompat with php 7.1

---

templates/app/team.phtml

Remove Twitter link, change bio

Remove Twitter link, change bio in team.phtml

---

public/.htaccess

Force all traffic onto www. so cookies for session work properly

---

src/App/Entity/Meetup.php
src/App/Entity/User.php

Fixed entity relationship mapping for persist/remove/orphan

---

README.md
data/migrations/Version20161005104033.php
data/migrations/Version20170712151355.php
docker-compose.yml
docker/nginx/Dockerfile
docker/nginx/nginx.conf
docker/php-fpm/Dockerfile
docker/php-fpm/php-fpm.conf
docker/php-fpm/php-overrides.ini
docker/postgres/Dockerfile
docker/postgres/initdb.d/enable-pgcrypto.sql
run-in-php-docker.sh

Added docker environment for easier setup

---

templates/layout/footer.phtml

Fix Slack link in footer

---

src/App/Service/Speaker/FlysystemMoveSpeakerHeadshot.php

Also when merged this should auto deploy to Heroku :+1:

Fix CS issue in build

---

README.md
config/autoload/local.php.dist
data/migrations/create-sample-fixtures.php
data/migrations/sample-fixtures.sql

Seed data and updated setup instructions
